### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by ashutoshsingh0223**
Put an = after ENV variable

### CODE REVIEW

**Comment by alfg** [comment]
Thanks for the PR. Can you also add the change  to the ffmpeg image too?

**Comment by ashutoshsingh0223** [comment]
Okay I will

**Comment by ashutoshsingh0223** [comment]
> Thanks for the PR. Can you also add the change to the ffmpeg image too?

Done

**Comment by alfg** [comment]
Thanks!

**Pull request merged**
